services:
  - type: web
    name: careernova-ai-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn ai-service.main:app --host 0.0.0.0 --port %%PORT%%"
    autoDeploy: true
